### ISSUE TITLE
IP associate & "Path ip is required"

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-client-go#5]
> Przy associate IP dostaję "allowBody_98 validation failed: ip: Path ip is required."
> 
> Biblioteka wysyła body: {"ip":"5c46f923d7760a51fc44ae79"}
> 
> Ścieżka: /ip/5784e97be2627505227b585e/actions/associate

**Comment by fredericosilva** [comment]
@ad-m fixed
